Devalop/apps/academia_web/lib/academia_web/router.ex
defmodule AcademiaWeb.Router do
  use AcademiaWeb, :router

  require Ueberauth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end
  
  scope "/auth", AcademiaWeb do
    pipe_through [:browser]
    
    get "/login", AuthController, :index
    get "/logout", AuthController, :logout
    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
    post "/:provider/callback", AuthController, :callback
  end

  scope "/trainers", AcademiaWeb do
    pipe_through [:browser]
    
    resources "/workshops", TrainerWorkshopController
    resources "/topics", TrainerTopicController
    resources "/tasks", TrainerTaskController
  end

  scope "/", AcademiaWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    resources "/workshops", WorkshopController
    resources "/topics", TopicController
    resources "/tasks", TaskController
  end

  scope "/api", AcademiaWeb do
    pipe_through :api

    put "/tasks/completed", TopicController, :update
  end
end

Devalop/apps/academia_web/lib/academia_web/templates/trainer_topic/show.html.eex
<div class="row">
  <div class="col-sm-12">
    <button type="button" class="btn btn-default waves-effect waves-light pull-right" data-toggle="modal" data-target="#task-form-modal"><i class="fa fa-plus"></i> Add Task</button>
    <h4 class="page-title"><%= @topic.name %></h4>
    <p class="text-muted page-title-alt">List of available tasks for <%= @topic.event_workshop.workshop.name %> Workshop</p>
  </div>

  <div class="col-lg-12">
    <%= if(length(@topic.items) > 0) do %>
      <div class="card-box">
      <ul class="sortable-list taskList list-unstyled" id="upcoming">
        <%= for item <- @topic.items do %>
          <li class="task-default">
            <!--
            <div class="checkbox checkbox-custom checkbox-single pull-right">
                <input type="checkbox" aria-label="Single checkbox Two">
                <label></label>
            </div>
            -->
            <div class="m-b-10">
              <p class="pull-right">
                <button class="btn btn-sm btn-purple" data-toggle="modal" data-target="#<%= item.id %>">Edit</button>
                <%= button("Delete", to: "/trainers/tasks/#{item.id}", method: "delete", class: "btn btn-sm btn-danger") %>
              </p>
              <p class="m-b-0"><span class="font-bold"><%= item.name %></span></p>
            </div>
            <%= raw(item.description) %>
          </li>
          <div id="<%= item.id %>" class="modal fade" tabindex="-1" role="dialog">
            <div class="modal-dialog">
              <div class="modal-content p-0 b-0">
                <div class="panel panel-color panel-purple">
                  <div class="panel-heading"> 
                    <button type="button" class="close m-t-5" data-dismiss="modal" aria-hidden="true">×</button> 
                    <h3 class="panel-title">Edit Task</h3> 
                  </div> 
                  <div class="panel-body">
                      <%= form_for @conn, trainer_task_path(@conn, :update, item.id), [method: "PUT", as: :update_topic_task], fn f -> %>
                        <%= hidden_input(f, :topic_id, value: @topic.id) %>
                        <div class="form-group">
                          <label class="control-label">Task</label>
                          <%= text_input f, :name, [value: item.name, class: "form-control"] %>
                        </div>
                        <div class="form-group">
                          <label class="control-label">Description</label>
                          <%= textarea f, :description, [class: "form-control", value: item.description] %>
                        </div>
                        <div class="form-group text-right">
                          <button class="btn btn-purple" type="submit">Save</button>
                        </div>
                      <% end %>
                  </div> 
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </ul>
    </div>
    <%= else %>
      <div class="col-lg-12">
      <div class="panel panel-default">
        <div class="panel-body text-center">
          <h4 class="text-muted">Ooops! Sorry No items available for this topic.</h4>
          <%= link("View All Topics", to: "/trainers/workshops/#{@topic.event_workshop.workshop.slug}", class: "btn btn-purple m-t-20") %>
        </div>
      </div>
    </div>
    <% end %>
  </div>

  <div id="task-form-modal" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content p-0 b-0">
        <div class="panel panel-color panel-purple">
          <div class="panel-heading"> 
            <button type="button" class="close m-t-5" data-dismiss="modal" aria-hidden="true">×</button> 
            <h3 class="panel-title">Add Task</h3> 
          </div> 
          <div class="panel-body">
              <%= form_for @conn, trainer_task_path(@conn, :create), [as: :add_topic_task], fn f -> %>
                <%= hidden_input(f, :topic_id, value: @topic.id) %>
                <div class="form-group">
                  <label class="control-label">Task</label>
                  <%= text_input f, :name, [class: "form-control"] %>
                </div>
                <div class="form-group">
                  <label class="control-label">Description</label>
                  <%= textarea f, :description, [class: "form-control"] %>
                </div>
                <div class="form-group text-right">
                  <button class="btn btn-purple" type="submit">Save</button>
                </div>
              <% end %>
          </div> 
        </div>
      </div>
    </div>
  </div>
</div>