Devalop/apps/academia_web/lib/academia_web/router.ex
defmodule AcademiaWeb.Router do
  use AcademiaWeb, :router

  require Ueberauth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end
  
  scope "/auth", AcademiaWeb do
    pipe_through [:browser]
    
    get "/login", AuthController, :index
    get "/logout", AuthController, :logout
    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
    post "/:provider/callback", AuthController, :callback
  end

  scope "/trainers", AcademiaWeb do
    pipe_through [:browser]
    
    resources "/workshops", TrainerWorkshopController
    resources "/topics", TrainerTopicController
    resources "/tasks", TrainerTaskController
  end

  scope "/", AcademiaWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    resources "/workshops", WorkshopController
    resources "/topics", TopicController
    resources "/tasks", TaskController
  end

  scope "/api", AcademiaWeb do
    pipe_through :api

    put "/tasks/completed", TopicController, :update
  end
end

Devalop/apps/academia_web/lib/academia_web/views/trainer_workshop_view.ex
defmodule AcademiaWeb.TrainerWorkshopView do
  use AcademiaWeb, :view

  def get_image_path(image_file) do
    {:ok, path} = File.cwd()
    "#{path}/apps/academia_web/priv/static/images/trainers/#{image_file}"
  end
end

Devalop/apps/academia_web/lib/academia_web/templates/trainer_workshop/index.html.eex
<div class="row">

  <div class="col-sm-12">
      <h4 class="page-title">Workshops</h4>
      <p class="text-muted page-title-alt">List of available workshops</p>
  </div>

  <%= for workshop <- @workshops do %>
    <div class="col-lg-4 workshop-card">
      <div class="card-box p-0">
        <div class="profile-widget text-center">
            <%= if(File.exists?(get_image_path("#{workshop.workshop.slug}.jpg"))) do %>
              <%= img_tag(static_path(@conn, "/images/trainers/#{workshop.workshop.slug}.jpg"), class: "thumb-lg img-circle img-thumbnail" ) %>
            <%= else %>
              <%= img_tag(static_path(@conn, "/images/I0pBwxh6.jpg"), class: "thumb-lg img-circle img-thumbnail" ) %>
            <% end %>
            <h4><%= workshop.workshop.name %></h4>
            <p class="text-muted">Meetup #2</p>
            <%= link("View Workshop", to: "/trainers/workshops/#{workshop.workshop.slug}", class: "btn btn-sm btn-purple m-t-10") %>
            <ul class="list-inline widget-list clearfix">
                <li class="col-md-4"><span><%= length(workshop.topics) %></span>Topics</li>
                <li class="col-md-4"><span>0</span>Tasks</li>
                <li class="col-md-4"><span>0</span>Students</li>
            </ul>
        </div>
      </div>
    </div>
  <% end %>
</div>

Devalop/apps/academia_web/lib/academia_web/templates/trainer_workshop/show.html.eex
<div class="row">
  <div class="col-sm-12">
    <button type="button" class="btn btn-default waves-effect waves-light pull-right" data-toggle="modal" data-target="#topic-form-modal"><i class="fa fa-plus"></i> Add Topic</button>
    <h4 class="page-title"><%= @workshop.name %> Workshop</h4>
    <p class="text-muted page-title-alt">List of available topics</p>
  </div>

  <%= if(length(@topics) > 0) do %>
    <%= for topic <- @topics do %>
      <div class="col-lg-4 workshop-card">
        <div class="card-box p-0">
          <div class="profile-widget text-center">
              <%= img_tag(static_path(@conn, "/images/I0pBwxh6.jpg"), class: "thumb-lg img-circle img-thumbnail" ) %>
              <h4><%= topic.name %></h4>
              <%= link("View", to: "/trainers/topics/#{topic.id}", class: "btn btn-sm btn-purple m-t-10") %>
              <button class="btn btn-sm btn-purple m-t-10" data-toggle="modal" data-target="#<%= topic.id %>">Edit</button>
              <%= button("Delete", to: "/trainers/topics/#{topic.id}", method: "delete", class: "btn btn-sm btn-danger m-t-10") %>
              <ul class="list-inline widget-list clearfix">
                  <li class="col-md-6"><span><%= length(topic.items) %></span>Tasks</li>
                  <li class="col-md-6"><span>0 %</span>Completion</li>
              </ul>
          </div>
        </div>
      </div>

      <div id="<%= topic.id %>" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog">
          <div class="modal-content p-0 b-0">
            <div class="panel panel-color panel-purple">
              <div class="panel-heading"> 
                <button type="button" class="close m-t-5" data-dismiss="modal" aria-hidden="true">×</button> 
                <h3 class="panel-title">Edit Topic</h3> 
              </div> 
              <div class="panel-body">
                  <%= form_for @conn, trainer_topic_path(@conn, :update, topic.id), [method: "PUT", as: :update_topic], fn f -> %>
                    <div class="form-group">
                      <label class="control-label">Topic</label>
                      <%= text_input f, :name, [class: "form-control", value: topic.name] %>
                    </div>
                    <div class="form-group text-right">
                      <button class="btn btn-purple" type="submit">Save</button>
                    </div>
                  <% end %>
              </div> 
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <%= else %>
    <div class="col-lg-12">
      <div class="panel panel-default">
        <div class="panel-body text-center">
          <h4 class="text-muted">Ooops! Sorry No topics available for this workshop.</h4>
          <%= link("View All Workshops", to: "/workshops", class: "btn btn-purple m-t-20") %>
        </div>
      </div>
    </div>
  <% end %>

  <div id="topic-form-modal" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content p-0 b-0">
        <div class="panel panel-color panel-purple">
          <div class="panel-heading"> 
            <button type="button" class="close m-t-5" data-dismiss="modal" aria-hidden="true">×</button> 
            <h3 class="panel-title">Add Topic</h3> 
          </div> 
          <div class="panel-body">
              <%= form_for @conn, trainer_topic_path(@conn, :create), [as: :add_topic], fn f -> %>
                <%= hidden_input(f, :workshop_event_id, value: @workshop.id) %>
                <div class="form-group">
                  <label class="control-label">Topic</label>
                  <%= text_input f, :name, [class: "form-control"] %>
                </div>
                <div class="form-group text-right">
                  <button class="btn btn-purple" type="submit">Save</button>
                </div>
              <% end %>
          </div> 
        </div>
      </div>
    </div>
  </div>
</div>